export const toggleNode = 'TOGGLE_NODE'
export const removeNode = 'REMOVE_NODE'
export const addNode = 'ADD_NODE'
export const openNewNodeDialog = 'OPEN_NEW_NODE_DIALOG'
export const closeNewNodeDialog = 'CLOSE_NEW_NODE_DIALOG'
export const changeNewNodeName = 'CHANGE_NEW_NODE_NAME'